server:
  port: 8080
spring:
  freemarker:
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
  profiles:
    active: dev

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml